### ISSUE TITLE
bug: pyarrow backend raises with `.group_by('a').agg(c=nw.col('b').sum(), d=nw.col('b').sum())`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1612]
```python
import pyarrow as pa
import narwhals as nw
import pandas as pd
import polars as pl

data = {"a": [1, 1, 1, 1, 1, 2, 2, 2, 2, 2], "b": list(range(10))}

nw.from_native(pa.table(data)).group_by('a').agg(c=nw.col('b').sum(), d=nw.col('b').sum())
```
```
$ python t.py 
Traceback (most recent call last):
  File "/home/marcogorelli/polars-api-compat-dev/t.py", line 13, in <module>
    nw.from_native(pa.table(data)).group_by('a').agg(c=nw.col('b').sum(), d=nw.col('b').sum())
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/group_by.py", line 114, in agg
    self._grouped.agg(*aggs, **named_aggs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/_arrow/group_by.py", line 83, in agg
    return agg_arrow(
           ^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/_arrow/group_by.py", line 191, in agg_arrow
    ).select(output_names)
      ^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4330, in pyarrow.lib.Table.select
  File "pyarrow/table.pxi", line 1715, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "c" does not exist in schema'
```

**Comment by FBruzzesi** [comment]
So does pandas:

```py
nw.from_native(pd.DataFrame(data)).group_by('a').agg(c=nw.col('b').sum(), d=nw.col('b').sum())
```

> ColumnNotFoundError: The following columns were not found: ['c']
>
> Hint: Did you mean one of these columns: ['a', 'd', 'd']?
