### ISSUE TITLE
[Bug]: PyArrow: multi-element `__getitem__` is not supported

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#947]
### Describe the bug

The code below raises
```python
Traceback (most recent call last):
  File "/home/marcogorelli/polars-api-compat-dev/t.py", line 20, in <module>
    print(func(pa.table(data)))
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/translate.py", line 717, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/t.py", line 16, in func
    return df['a'][[0, 1]]
           ~~~~~~~^^^^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/series.py", line 57, in __getitem__
    return self._from_compliant_series(self._compliant_series[idx])
                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/marcogorelli/polars-api-compat-dev/narwhals/_arrow/series.py", line 318, in __getitem_
_
    return self._from_native_series(self._native_series[idx])
                                    ~~~~~~~~~~~~~~~~~~~^^^^^
  File "pyarrow/table.pxi", line 306, in pyarrow.lib.ChunkedArray.__getitem__
TypeError: 'list' object cannot be interpreted as an integer
```

### Steps or code to reproduce the bug

```python
# ruff: noqa

import polars as pl
import narwhals as nw
import pandas as pd
import duckdb
import pandas as pd
import pyarrow as pa
import dask.dataframe as dd

data = {'a': [1, 1, 2], 'b': [5, 4, 3]}


@nw.narwhalify
def func(df):
    return df['a'][[0, 1]]

print(func(pd.DataFrame(data)))
print(func(pl.DataFrame(data)))
print(func(pa.table(data)))
```

### Expected results

Equivalent of
```
0    1
1    1
Name: a, dtype: int64
shape: (2,)
Series: 'a' [i64]
[
        1
        1
]
```
for pandas/Polars

### Actual results

error

### Please run narwhals.show_version() and enter the output below.

```shell
System:
    python: 3.11.9 (main, Jul 25 2024, 22:42:09) [Clang 18.1.8 ]
executable: /home/marcogorelli/polars-api-compat-dev/.venv/bin/python
   machine: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
     narwhals: 1.6.3
       pandas: 2.2.2
       polars: 1.6.0
         cudf: 
        modin: 
      pyarrow: 17.0.0
        numpy: 2.1.1
```

**Comment by raisadz** [comment]
I will take it
